module.exports = {
	createTable
}

function createTable(tableName){
	return `CREATE TABLE ${tableName} (
\t\`root_id\` BIGINT(19) NOT NULL AUTO_INCREMENT COMMENT 'root_id',
\t\`vod_id\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`type_id\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`type_id_1\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`group_id\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_name\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_sub\` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_en\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_status\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_letter\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_color\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_tag\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_class\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_pic\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_pic_thumb\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_pic_slide\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_pic_screenshot\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_actor\` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_director\` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_writer\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_behind\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_blurb\` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_remarks\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_pubdate\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_total\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_serial\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_tv\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_weekday\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_area\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_lang\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_year\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_version\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_state\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_author\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_jumpurl\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_tpl\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_tpl_play\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_tpl_down\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_isend\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_lock\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_level\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_copyright\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_points\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_points_play\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_points_down\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_hits\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_hits_day\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_hits_week\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_hits_month\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_duration\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_up\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_down\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_score\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_score_all\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_score_num\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_time\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_time_add\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_time_hits\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_time_make\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_trysee\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_douban_id\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_douban_score\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_reurl\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_rel_vod\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_rel_art\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_pwd\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_pwd_url\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_pwd_play\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_pwd_play_url\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_pwd_down\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_pwd_down_url\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_content\` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_play_from\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_play_server\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_play_note\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_play_url\` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_down_from\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_down_server\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_down_note\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_down_url\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_plot\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_plot_name\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`vod_plot_detail\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\t\`type_name\` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
\tPRIMARY KEY (\`root_id\`) USING BTREE
)
COMMENT='root'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
`
}